### ISSUE TITLE
[Bug]: Install issue

### ISSUE THREAD

**Issue by asadbek-fayzulloev** [lara-zeus/wind#69]
### What happened?

I cannot install lara-zeus pacakge because when I type "composer require lara-zeus/wind" command on terminal, it gives "  Call to a member function hasPlugin() on null"

### How to reproduce the bug

@php artisan package:discover --ansi

   Error 

  Call to a member function hasPlugin() on null

  at vendor/filament/filament/src/FilamentManager.php:535
    531▕     }
    532▕ 
    533▕     public function hasPlugin(string $id): bool
    534▕     {
  ➜ 535▕         return $this->getCurrentPanel()->hasPlugin($id);
    536▕     }
    537▕ 
    538▕     public function hasProfile(): bool
    539▕     {

      +10 vendor frames 

  11  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(LaraZeus\Wind\WindServiceProvider))
      +5 vendor frames 

  17  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### Package Version

3.0.2

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by atmonshi** [comment]
It look like you have an older version of filament
Can you check by running:

`php artisan about`

or 
`composer show filament/filament`

Edit:
you can update filament using:

`composer require filament/filament:"^3.0-stable" -W`
