### ISSUE TITLE
Add ability to add captcha

### ISSUE THREAD

**Issue by klytron** [lara-zeus/wind#85]
I wanted to add a captcha plugin for example https://filamentphp.com/plugins/ousid-cloudflare-turnstile but can't seem to make it work.

**Comment by atmonshi** [comment]
its not possible now to do that
you would need to copy the resource from the vendor folder to your app folder and add any features you need.

**Comment by klytron** [comment]
do you mean resources/views/vendor/zeus/themes/zeus/wind/contact-form.blade.php ?  I tried that by publishing the resource files but didn't work.

**Comment by atmonshi** [comment]
not the views, you need this file:
`vendor/lara-zeus/wind/src/Livewire/ContactsForm.php`
copy it to your app, change the namespace and set a route for it.

then you can add any fields or components you want

**Comment by klytron** [comment]
Thanks that worked.
